// autogenerated from generate-api-docs.js

export interface NavItem {
  title: string
  href?: string
  items?: NavItem[]
}

export interface NavSection {
  title: string
  items: NavItem[]
}

export const docsNavigation: NavSection[] = [
  {
    title: 'Getting Started',
    items: [
      {
        title: 'Introduction',
        href: '/docs',
      },
    ],
  },
  {
    title: 'Core Concepts',
    items: [
      {
        title: 'Organizations',
        href: '/docs/organizations',
      },
      {
        title: 'Projects',
        href: '/docs/projects',
      },
      {
        title: 'Usage & Analytics',
        href: '/docs/usage',
      },
    ],
  },
  {
    title: 'API Reference',
    items: [
      {
        title: 'Overview',
        href: '/docs/api',
      },
      {
        title: 'API Documentation',
        items: [
          {
            title: 'Authentication',
            href: '/docs/api/authentication',
          },
          {
            title: 'Users',
            href: '/docs/api/users',
          },
          {
            title: 'Organizations',
            href: '/docs/api/organizations',
          },
          {
            title: 'Projects',
            href: '/docs/api/projects',
          },
          {
            title: 'API Keys',
            href: '/docs/api/api-keys',
          },
          {
            title: 'Audit',
            href: '/docs/api/audit',
          },
          {
            title: 'Subscriptions',
            href: '/docs/api/subscriptions',
          },
          {
            title: 'Usage',
            href: '/docs/api/usage',
          },
          {
            title: 'Webhooks',
            href: '/docs/api/webhooks',
          },
          {
            title: 'Shopify',
            href: '/docs/api/shopify',
          },
          {
            title: 'Shopify AEO',
            href: '/docs/api/shopify-aeo',
          },
          {
            title: 'AEO Analysis',
            href: '/docs/api/aeo-analysis',
          },
          {
            title: 'AEO Visibility',
            href: '/docs/api/aeo-visibility',
          }
        ],
      },
    ],
  },
  {
    title: 'Integrations',
    items: [
      {
        title: 'Webhooks',
        href: '/docs/webhooks',
      },
    ],
  },
]
